---
apiVersion: v1
kind: Service
metadata:
  name: consumerservice
  labels:
    app: consumerservice
spec:
  type: NodePort
  selector:
    app: consumerservice
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: consumerservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consumerservice
    spec:
      containers:
      - name: consumerservice
        image: rsoprojectwut/consumerservice:0.0.2
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
